version: '3.8'

services:
  flask_app:
    build:
      context: ./
    ports:
      - "5001:5001"
    networks:
      - app_network

  streamlit_app:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - flask_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
